# Generated by Django 4.2.4 on 2025-01-31 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='eaglebucks',
            field=models.IntegerField(null=0),
        ),
    ]
